<div id="Hatalar" class="uyari">
	<fieldset>
		<legend>PHP Hatalar</legend>
		<pre id="phpHatalari" name="phpHatalari" contenteditable="true">
		<?php echo $this->hatalar ?>
		</pre>
		<a href="#" id="phpHatalariTemizle" name="phpHatalariTemizle">Kaydet</a>     
	</fieldset>   
	<fieldset>
		<legend>PHP Exception</legend>
		<pre id="phpEx" name="phpEx" contenteditable="true">
		<?php echo $this->hatalarEX ?>
		</pre>
		<a href="#" id="phpExTemizle" name="phpExTemizle">Kaydet</a>     
	</fieldset>   
	<fieldset>
		<legend>Javascript Hatalar</legend>
		<pre id="JS" name="JS" contenteditable="true">
		<?php echo $this->hatalarJS ?>
		</pre>
		<a href="#" id="JSTemizle" name="JSTemizle">Kaydet</a>     
	</fieldset>   
</div>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" ></script>
<script>
$(document).ready(function() {
	$.ajaxSetup({
		type: 'POST',
		timeout: 5000,  
		cache: false,
		url: '/main/admin/hata'
	});

	$('#phpHatalariTemizle').click(function(){$.ajax({data: 'silHatalar='+$('#phpHatalari').html()});return false;});
	$('#phpExTemizle').click(function(){$.ajax({data: 'silEx='+$('#phpEx').html()});return false;});
	$('#JSTemizle').click(function(){$.ajax({data: 'silJS='+$('#JS').html()});return false;});
});
</script>
