	<div class="tabs">
		<div id="Grup">
			<a href="#" class="button" id="adyg">Yeni Grup</a><br />
			<form>
				<label for="ytur">Yeni Tür:</label>
				<input name="ytur" size="45" required />
			</form><br class="clear" /><hr />
			<form>
				<label for="ymem">Yeni Ülke:</label>
				<input name="ymem" size="45" required />
			</form><br class="clear" /><hr />
			<form id="adgas">
				<label for="gsec">Müzisyen:</label>
				<select name="gsec">
				<?php
					foreach($this->muzik as $row)
						echo "<option value=$row[id] id=$row[id]>$row[ad]</option>";
				?>
				</select>
				<span class="checkBlue">Seç</span>
				<span class="thrashBlue">Sil</span>
			</form><br class="clear" /><hr />
			<form id="asggf">
				<input type="hidden" name="id" id="id" value="0" />
				<p>
					<label for="ad">Ad:</label>
					<input name="ad" size="45" required />
				</p>
				<p>
					<label for="tur">Tür:</label>
					<select name="tur" required>
					<?php
						foreach($this->tur as $row)
							echo "<option value=$row[id] id=$row[id]>$row[ad]</option>";
					?>
					</select>
				</p>
				<p>
					<label for="mem">Memleket:</label>
					<select name="mem" required>
					<?php
						foreach($this->mem as $row)
							echo "<option value=$row[id] id=$row[id]>$row[ad]</option>";
					?>
					</select>
				</p>
				<p>
					<label for="clip">Klip:</label>
					<input type="url" name="clip" size="45" required />
				</p>
				<p>
					<label for="tanim">Tanım:</label>
					<textarea id="tanim" name="tanim" class="cleditor" rows="13" cols="50" placeholder="Öz geçmiş" required ></textarea>
				</p>
				<p>
					<input type="submit" id="ggun" value="Guncelle" />
					<input type="submit" id="gkay"/>
				</p>
			<hr />
			</form>
			<br />
			<div id="forUpdate">
				<fieldset id="alform">
					<legend>Albümler</legend>
					<form>
						<input name="alad" placeholder="Albüm" required/>
						<input type="number" name="alyil" min="1900" max="2020" step="1" placeholder="Yıl" required/>
						<input type="submit"/>
					</form>
					<select></select>
					<span class="thrashBlue">Sil</span>
				</fieldset><hr />
				<fieldset id="elform">
					<legend>Elemanlar</legend>
					<form>
						<input id="elad" placeholder="Müzisyen" required/>
						<input id="elens" placeholder="Enstrümanı" required/>
						<input type="submit"/>
					</form>
					<select></select>
					<span class="thrashBlue">sil</span>
				</fieldset>
			</div>
			<fieldset id="ruf">
				<div id="resimUpload">Resim Yükle</div>
				<img src="" />
			</fieldset>
		</div>
		<div id="film">
			<h3>Film İşlemleri</h3>
			<br class="clear" />
			<form>
				<p><label for="fad">Ad:</label><input name="fad" size="250" placeholder="Big Buck Bunny" required /></p>
				<p><label for="uz">Uzunluk:</label><input type="time" name="uz" size="25" placeholder="15:00" required /></p>
				<p><label for="mp4">MP4:</label><input type="url" name="mp4" size="45" /></p>
				<p><label for="ogg">OGG:</label><input type="url" name="ogg" size="45" /></p>
				<p><label for="webm">WEBM:</label><input type="url" name="webm" size="45" /></p>
				<p><label for="tube">Youtube:</label><input name="tube" size="45" /></p>
				<p><label for="ac">Desc:</label><input type="url" name="ac" size="45" /></p>
				<p><label for="chap">Chap:</label><input type="url" name="chap" size="45" /></p>
				<p><label for="meta">Meta:</label><input type="url" name="meta" size="45" /></p>
				<p><label for="en">En:</label><input type="url" name="en" size="45" /></p>
				<p><label for="tr">Tr:</label><input type="url" name="tr" size="45" /></p>
				<p><input type="submit"/></p>
			</form>
		</div>
	</div>
</div>

<aside id="rcnt" role=”complementary”>
<ul class="adtn">
	<li><a class="button" href="#Grup">Müzik İşlemleri</a></li>
	<li><a class="button" href="#film">Film İşlemleri</a></li>
	<li><a class="button popUpper" href="#Grup" id="<?php echo $this->url(array(), 'hata'); ?>">Hatalar</a></li>
	<li><a class="button popUpper" href="#Grup" id="<?php echo $this->url(array(), 'sunucu'); ?>">Sunucu Kontrol</a></li>
	<li><a class="button popUpper" href="#Grup" id="<?php echo $this->url(array(), 'stats'); ?>">Ziyaretçiler</a></li>
	<li><a class="button popUpper" href="#Grup" id="<?php echo $this->url(array(), 'abuse'); ?>">Tacizciler</a></li>
	<li><a class="button popUpper" href="#Grup" id="<?php echo $this->url(array(), 'api'); ?>">API</a></li>
	<li><a class="button popUpper" href="#Grup" id="<?php echo $this->url(array(), 'midware'); ?>">HTACCESS</a></li>
	<li><a class="button popUpper" href="#Grup" id="<?php echo $this->url(array(), 'hiz'); ?>">HIZ</a></li>
	<li><a class="button popUpper" href="#Grup" id="<?php echo $this->url(array(), 'adsense'); ?>">Adsense</a></li>
	<li><a class="button popUpper" href="#Grup" id="<?php echo $this->url(array(), 'dosya'); ?>">Dosyalar</a></li>
	<li><a class="button popUpper" href="#Grup" id="<?php echo $this->url(array(), 'shell'); ?>">Shell</a></li>
	<li><a class="button popUpper" href="#Grup" id="<?php echo $this->url(array(), 'fulltext'); ?>">Arama</a></li>
</ul>
<div id="uyari" class="uyari" ></div>
