<style>	
/*<![CDATA[*/
@import "https://github.com/jquery/qunit/raw/master/qunit/qunit.css";
/*]]>*/
</style>
<script src="https://github.com/jquery/qunit/raw/master/qunit/qunit.js"></script>
<script src="/main/js/index.js"></script>  
<script src="/main/js/main.js"></script>
<script src="/main/js/test/test.js?"></script>  

<h1 id="qunit-header">QUnit Test Suite</h1>  
<h2 id="qunit-banner"></h2>  
<div id="qunit-testrunner-toolbar"></div>  
<h2 id="qunit-userAgent"></h2>  
<ol id="qunit-tests"></ol>  
