<table class="verification_table">
	<caption>PHP Gereklilik Kontrolcusu Calistirildi</caption>
	<tr><td colspan=2 class="verification_type"><strong>Genel Ayarlar</strong></td></tr>
	<?php echo $this->ini ?>
	<tr><td colspan=2 class="verification_type"><strong>Filtreler</strong></td></tr>
	<?php echo $this->filter ?>
	<tr><td colspan=2 class="verification_type"><strong>Veri Tabanlari</strong></td></tr>
	<?php echo $this->veriTabani ?>
	<tr><td colspan=2 class="verification_type"><strong>PDO Veritabani Suruculeri</strong></td></tr>
	<?php while(list(,$driver)=each($this->drivers))
		echo "<tr><td class=\"notError\"></td><td class=\"notError\">".$driver."</td></tr> "; 
	echo $this->phpFunction;
	echo $this->pear; ?>
	<tr><td colspan=2 class="verification_type"><strong>HASH Algoritmalari</strong></td></tr>
	<?php 
		while(list(,$algo)=each($this->algos))
			echo "<tr><td class=\"notError\"></td><td class=\"notError\">".$algo."</td></tr> ";
	?>
	<tr><td colspan=2 class="verification_type"><strong>Local Diller</strong></td></tr>
	<?php echo $this->local; ?>
</table>
