<div id="sctb" class="rounded" aria-live="polite" aria-atomic="true" ><p>Şu anda giriş yapmadınız!</p></div>
<div id="scbb" class="rounded" aria-live="assertive" aria-atomic="false" >
    	<div class="tip"></div>
	<form id="sclf">
	    <label for="name" class="sakla">İsim</label><input name="name" class="rounded" maxlength="16" placeholder="Takma Ad" required aria-required />
	    <label for="email" class="sakla">Email</label><input name="email" class="rounded" placeholder="Email (Gravatar etkin)" required aria-required />
	    <input type="submit" value="Gir"/>
	</form>
	<form id="scsf">
	    <label for="scct" class="sakla">Mesaj</label><input id="scct" name="scct" class="rounded" maxlength="255" aria-required required/>
	    <input type="submit" value="Yaz"/>
	</form>
</div>
<div id="sclh" aria-live="assertive" aria-atomic="true" ></div>
</div>

<aside id="rcnt" role=”complementary” aria-live="assertive" aria-atomic="true" >
	<?php echo $this->ara(); ?>
