<nav id="spc" role="navigation">
	<a id="mailA" href="#smp"><div><em>Mail</em></div></a>
	<a id="sssA" href="#ssp"><div><em>SSS</em></div></a>
	<a id="oneriA" href="#sop"><div><em>Öneri</em></div></a>
</nav>
<div id="sakliBlue" class="sakla page"></div>
<div class="page" id="smp">
	<header class="shs"><h3>Mail Gönder</h3><span id="uyari" class="uyari"></span></header>
	<form class="sss gradient">
		<p><label for="f">Kimden:</label><input type="email" name="f" size="30" required aria-required /></p>
		<p><label for="t">Kime:</label><input type="email" name="t" size="30" required aria-required list="mails" />
			<datalist id="mails">
			<?php 
				foreach($this->mail as $mail)
					echo "<option value='".$mail["Detay"]["aileBireyMail"]."'>".$mail["aileAd"]."</option>";
			?>
			</datalist>
		</p>
		<p><label for="h">Konu:</label><input name="h" size="30" required aria-required /></p>
		<label for="cleditor">Mesaj:</label><br class="clear" />
		<textarea cols="60" id="cleditor" class="cleditor" rows="13" required maxlength="500" aria-required ></textarea>
		<input type="submit" class="bonBonButton xs skew pink glass"/>
	</form>
</div>
<div class="page" id="ssp">
	<header class="shs"><h3>Sıkça Sorulan Sorular ?</h3></header>
	<div class="sss gradient"><a href="#" class="bonBonButton xs shield pink glass">Hepsini Göster</a></div>
</div>
<div class="page" id="sop">
	<header class="shs"><h3>Önerilerinizi Paylaşın</h3></header>
	<div class="sss gradient">
		<ul>
		<?php 
			foreach($this->oneri as $row)
			echo '<li class="border" id="s'.$row['id'].'">
				<div class="vote '.($row['hv'] ? 'inactive' : 'active').'">
					<a class="up" rev="vote-for" href="#">Evet</a>
					<a class="down" rev="vote-against" href="#">Hayır</a>
				</div>
				<div class="text">'.$row['oneri'].'</div>
				<div class="rating">'.$row['rating'].'</div>
			</li>';
		?>
		</ul>
		<form class="border" method="post">
			<label for="s">Öneri:</label>
			<input name="s" id="s" class="suggest" maxlength="255" required aria-required />
			<input type="submit" value="Kaydet"/>
		</form>
	</div>
</div>
</div>

<aside id="rcnt" role=”complementary”>
