<?php

/**
 * main_models_AileAgaci
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class main_models_Aa extends main_models_BaseAa
{
    public function setUp()
    {
        parent::setUp();
		$this->hasOne('main_models_Aad as Detay', array('local' => 'id','foreign' => 'id'));
		$this->hasOne('main_models_Aao as Oy', array('local' => 'id','foreign' => 'id'));
		$this->hasMany('main_models_Aay as Yorumlar', array('local' => 'id','foreign' => 'aileID')); 
		$this->hasOne('main_models_Aa as Ebeveyn', array('local' => 'eid','foreign' => 'id'));
        	$this->hasMany('main_models_Aa as Cocuklar', array('local' => 'id','foreign' => 'eid'));
    }

}
