<?php

/**
 * main_Models_AileAgaci
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class main_Models_AileAgaci extends main_Models_BaseAileAgaci
{
    public function setUp()
    {
        parent::setUp();
		$this->hasOne('main_Models_AileAgaciDetay as Detay', array('local' => 'aileID','foreign' => 'aileID'));
		$this->hasOne('main_Models_AileAgaciOy as Oy', array('local' => 'aileID','foreign' => 'aileID'));
		$this->hasMany('main_Models_Yorumlar as Yorumlar', array('local' => 'aileID','foreign' => 'aileID')); 
		$this->hasOne('main_Models_AileMap as Map', array('local' => 'aileID','foreign' => 'aileID')); 
		$this->hasOne('main_Models_AileAgaci as Ebeveyn', array('local' => 'ebeveynID','foreign' => 'aileID'));
        	$this->hasMany('main_Models_AileAgaci as Cocuklar', array('local' => 'aileID','foreign' => 'ebeveynID'));
    }

}
