<?php

/**
 * main_models_Appages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class main_models_Appages extends main_models_BaseAppages
{
    public function setUp()
    {
        parent::setUp();
		$this->hasMany('main_models_Apvotes as Oy', array('local' => 'id','foreign' => 'pageid')); 
    }

}
