<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('main_models_Ayarlar', 'doctrine');

/**
 * main_models_BaseAyarlar
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $yoneticiAd
 * @property string $sifre
 * @property string $gizliAnahtar
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class main_models_BaseAyarlar extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('ayarlar');
        $this->hasColumn('yoneticiAd', 'string', 25, array(
             'type' => 'string',
             'length' => 25,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('sifre', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('gizliAnahtar', 'string', 25, array(
             'type' => 'string',
             'length' => 25,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}
