<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('main_Models_OneriOy', 'doctrine');

/**
 * main_Models_BaseOneriOy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $oneri_id
 * @property integer $ip
 * @property date $gun
 * @property integer $oy
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class main_Models_BaseOneriOy extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('oneri_oy');
        $this->hasColumn('oneri_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('ip', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('gun', 'date', null, array(
             'type' => 'date',
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('oy', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
    }
}