<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('main_Models_AileAgaciDetay', 'doctrine');

/**
 * main_Models_BaseAileAgaciDetay
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $aileID
 * @property blob $aileResim
 * @property string $aileTanim
 * @property date $aileDogum
 * @property date $aileOlum
 * @property string $aileBireyEs
 * @property string $aileBireyAdres
 * @property string $aileBireyMail
 * @property integer $aileBireyTel
 * @property string $aileBireyMSN
 * @property string $aileBireyTwitter
 * @property string $aileBireyFlickr
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class main_Models_BaseAileAgaciDetay extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('aile_agaci_detay');
        $this->hasColumn('aileID', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('aileTanim', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('aileDogum', 'date', null, array(
             'type' => 'date',
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'past' => true,
             ));
        $this->hasColumn('aileOlum', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00',
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('aileBireyEs', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('aileBireyAdres', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('aileBireyMail', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('aileBireyTel', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('aileBireyMSN', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('aileBireyTwitter', 'string', 15, array(
             'type' => 'string',
             'length' => 15,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('aileBireyFlickr', 'string', 15, array(
             'type' => 'string',
             'length' => 15,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        $this->actAs('Timestampable');
        $this->actAs('Versionable', array(
                'versionColumn' => 'version',
                'className' => 'aile_agaci_detay_version',
                'auditLog' => true
               // 'generateFiles'   => true,
               // 'generatePath'    => '/path/to/generate'
            )
        );
        $this->actAs('SoftDelete');
        parent::setUp();
    }
}
