<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('main_Models_Eleman', 'doctrine');

/**
 * main_Models_BaseEleman
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $elemanID
 * @property string $elemanAd
 * @property string $enstruman
 * @property integer $grupID
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class main_Models_BaseEleman extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('eleman');
        $this->hasColumn('elemanID', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('elemanAd', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('enstruman', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('grupID', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}