<?php

/**
 * main_models_Album
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class main_models_Dmm extends main_models_BaseDmm
{
    public function setUp()
    {
        parent::setUp();
		$this->hasMany('main_models_Dm as Grup', array('local' => 'id','foreign' => 'mem'));
    }

}
