<?php

/**
 * main_Models_Muzik
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class main_Models_Muzik extends main_Models_BaseMuzik
{
    public function setUp()
    {
        parent::setUp();
		$this->hasMany('main_Models_Album as Albumler', array('local' => 'grupID','foreign' => 'grupID'));
		$this->hasMany('main_Models_Eleman as Elemanlar', array('local' => 'grupID','foreign' => 'grupID'));
    }

}