<?php

/**
 * main_Models_Oneri
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class main_Models_Oneri extends main_Models_BaseOneri
{
    public function setUp()
    {
        parent::setUp();
		$this->hasMany('main_Models_OneriOy as Oylar', array('local' => 'id','foreign' => 'oneri_id'));
    }

}