<?php

/**
 * main_Models_OneriOy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class main_Models_OneriOy extends main_Models_BaseOneriOy
{
    public function setUp()
    {
        parent::setUp();
		$this->hasOne('main_Models_Oneri', array('local' => 'oneri_id','foreign' => 'id'));
    }
}