	<div id="filmDiv" class="hreview" aria-live="assertive" aria-atomic="true" >
		<video id="movies" onplay="startVideo()" onended="stopTimeline()" onpause="stopTimeline()" preload="auto" controls class="item">
			<source src="<?php echo $this->film['mp4']; ?>" type='video/mp4'></source>
			<source src="<?php echo $this->film['webm']; ?>" type='video/webm'></source>
			<source src="<?php echo $this->film['ogg']; ?>" type='video/ogg'></source>
			<track src="<?php echo $this->film['ac']; ?>" kind="descriptions" srclang="en" />
			<track src="<?php echo $this->film['chap']; ?>" kind="chapters" srclang="en" />
			<track src="<?php echo $this->film['en']; ?>" kind="subtitles" srclang="en" />
			<track src="<?php echo $this->film['tr']; ?>" kind="subtitles" srclang="tr" />
			<track src="<?php echo $this->film['meta']; ?>" kind="metadata" srclang="en" />
			<object>
				<param name="movie" value="http://www.youtube.com/v/<?php echo $this->film['tube']; ?>?version=3">
				<param name="allowFullScreen" value="true">
				<param name="allowScriptAccess" value="always">
				<embed src="http://www.youtube.com/v/<?php echo $this->film['tube']; ?>?version=3" type="application/x-shockwave-flash" allowfullscreen="true" allowScriptAccess="always">
			</object>
		</video>
		<p class='uyari'><b>İndir:</b>
			Kapalı Format:	<a class="url" target='_blank' href="<?php echo $this->film['mp4']; ?>">'MP4'</a> 
			Açık Format:	<a class="url" target='_blank' href="<?php echo $this->film['ogg']; ?>">'OGG'</a>
			Google Format:	<a class="url" target='_blank' href="<?php echo $this->film['webm']; ?>">'WEBM'</a>
		</p><br />
		<a target='_blank' class='panelA' title="<?php echo $this->film['ad']; ?>" href="<?php echo $this->href; ?>" rel="bookmark"><img class="photo" src="<?php echo $this->poster; ?>" alt="<?php echo $this->film['ad']; ?>"></a>
		<h3 class="fn"><?php echo $this->film["ad"] ?></h3>
		<p class="rating"><b>Rating:</b><span class="value"><?php echo $this->rating; ?></span>/<span class="best">10</span></p>
		<p><b>Dil:</b><?php echo $this->dil; ?></p>
		<p><b>Yıl:</b><time pubdate><?php echo $this->released; ?></time></p>
		<p class="summary"><?php echo $this->overview; ?></p>
	</div>	
	<br class="clear" />
	<h4 id="cnvHed"></h4>
	<canvas id="timeline"></canvas>
	<p>Eğer siteye eklememizi istediğiniz bir film var ise arama kutusuna yazın.Filmler <a href='http://www.themoviedb.org/' target='_blank' title='The Movie Database'>TMDb</a> sitesinden alınıyor.</p>
	<table>
		<caption>Film İstekleri</caption>
		<thead>
			<tr><th></th><th>Film</th><th>Oy</th></tr>
		</thead>
		<tfoot>
			<tr>
				<td><?php echo count($this->istek); ?></td>
				<td>isteğe toplam</td>
				<td><?php
					function count_usr(&$item1, $key,&$s)
					{
						$s += $item1["istek"];
					}
					$s=0;
					array_walk($this->istek, 'count_usr',&$s);
					echo $s." oy verildi.";
					//echo array_sum($this->istek); 
				?></td>
			</tr>
		</tfoot>
		<tbody>
			<?php
			$i=0;
			foreach($this->istek as $istek)
				echo "<tr><td>".++$i."</td><td>".$istek["ad"]."</td><td>".$istek["istek"]."</td></tr>";
			?>
		</tbody>
	</table>
</div>
<aside id="rcnt" role=”complementary”>
	<form id="uzunluk-range">
		<p>
			<label for="m">En kısa:</label>
			<input type="range" id="m" name="m" value="0" min="0" max="40" step="5" aria-orientation= "vertical" role="slider" aria-valuemin="0" aria-valuemax="40" aria-valuenow="0" aria-valuetext="0" /> 
		</p>
		<!-- name değerlerini silme -->
		<p>
			<label for="x">En uzun:</label>
			<input type="range" id="x" name="x" value="45" min="5" max="45" step="5" aria-orientation= "vertical" role="slider" aria-valuemin="5" aria-valuemax="45" aria-valuenow="45" aria-valuetext="45" />
		</p>
	</form>
	<br />
	<?php if (count($this->records)): ?>
	<div id="pager">
	<?php echo $this->pages; ?>
	</div>
	<table>
	<thead>
		<tr>	
			<th class="key">
				<a class="upBlue" href="<?php echo $this->url(array('sort' => 'id','dir' => 'asc'), 'watch'); ?>"><?php echo $this->url(array('sort' => 'id','dir' => 'asc'), 'watch'); ?></a>
				Sıra
				<a class="downBlue" href="<?php echo $this->url(array('sort' => 'id','dir' => 'desc'), 'watch'); ?>"><?php echo $this->url(array('sort' => 'id','dir' => 'desc'), 'watch'); ?></a>
			</th>
		</tr>
		<tr>	
			<th class="key">
				<a class="upBlue" href="<?php echo $this->url(array('sort' => 'ad','dir' => 'asc'), 'watch'); ?>"><?php echo $this->url(array('sort' => 'ad','dir' => 'asc'), 'watch'); ?></a>
				Film
				<a class="downBlue" href="<?php echo $this->url(array('sort' => 'ad','dir' => 'desc'), 'watch'); ?>"><?php echo $this->url(array('sort' => 'ad','dir' => 'desc'), 'watch'); ?></a>
			</th>
		</tr>	
		<tr>	
			<th class="key">
				<a class="upBlue" href="<?php echo $this->url(array('sort' => 'uz', 'dir'=> 'asc'), 'watch'); ?>"><?php echo $this->url(array('sort' => 'uz', 'dir'=> 'asc'), 'watch'); ?></a>
				Süre
				<a class="downBlue" href="<?php echo $this->url(array('sort' => 'uz', 'dir'=> 'desc'), 'watch'); ?>"><?php echo $this->url(array('sort' => 'uz', 'dir'=> 'desc'), 'watch'); ?></a>
			</th>
		</tr>
	</thead>
	<tbody class="hreview">
		<?php foreach ($this->records as $r):?>
			<tr class="item">
				<td><h4 class="ui-widget ui-widget-header structured name"><?php echo $r['ad']; ?> (<time><?php echo $r['uz']; ?></time>)</h4><a class="url" rel="self bookmark" id="<?php echo $r['id']; ?>" href="?id=<?php echo $r['id']; ?>"><img class="photo" src="<?php echo $r['poster']; ?>" alt="<?php echo $r['ad']; ?>" title="<?php echo $r['ad']; ?>" /></a></td>
			</tr>
		<?php endforeach; ?>
	</tbody>
	</table>
	<?php else: ?>
	Kayıt bulunamadı!
	<?php endif; ?> 
