	<div id="accordion">
		<?php
		foreach ($this->muzik as $row)
		{
			echo "<h3>".$row["ad"]." </h3><div><table class='dmt'><tbody>";
			foreach($row["Grup"] as $g)
				echo "<tr><td><img title='".$g["ad"]." grubunun klibini izlemek için tıklayın' src='".getResim($g["id"],"muzik")."' id='".$g["clip"]."' alt='".$g["ad"]."' /></td><td><div class='".$g["Memleket"]["ad"]."'></div></td><td><a href='?id=".$g["id"]."' title='Devamını oku' id='".$g["id"]."'>".substr($g["tanim"],0,strrpos(substr($g["tanim"],0,150)," "))."...</a></td></tr>";
			echo "</tbody></table></div>";
		}
		?>
	</div>
	<br />
	<h3 class="ui-widget ui-widget-header">Emergent Collective One</h3>
	<div id="jquery_jplayer"></div>
	<div class="jp-playlist-player">
		<div class="jp-interface">
			<ul class="jp-controls">
				<li><a href="#" id="jplayer_play" class="jp-play" tabindex="1">Çal</a></li>
				<li><a href="#" id="jplayer_pause" class="jp-pause" tabindex="1">Durakla</a></li>
				<li><a href="#" id="jplayer_stop" class="jp-stop" tabindex="1">Dur</a></li>
				<li><a href="#" id="jplayer_volume_min" class="jp-volume-min" tabindex="1">Ses Kıs</a></li>
				<li><a href="#" id="jplayer_volume_max" class="jp-volume-max" tabindex="1">Ses Aç</a></li>
				<li><a href="#" id="jplayer_previous" class="jp-previous" tabindex="1">Önceki</a></li>
				<li><a href="#" id="jplayer_next" class="jp-next" tabindex="1">Sonraki</a></li>
			</ul>
			<div class="jp-progress">
				<div id="jplayer_load_bar" class="jp-load-bar">
					<div id="jplayer_play_bar" class="jp-play-bar"></div>
				</div>
			</div>
			<div id="jplayer_volume_bar" class="jp-volume-bar">
				<div id="jplayer_volume_bar_value" class="jp-volume-bar-value"></div>
			</div>
			<div id="jplayer_play_time" class="jp-play-time"></div>
			<div id="jplayer_total_time" class="jp-total-time"></div>
		</div>
		<div id="jplayer_playlist" class="jp-playlist">
			<ul>
				<!-- The function displayPlayList() uses this unordered list -->
				<li></li>
			</ul>
		</div>
	</div>
</div>

<aside id="rcnt" role=”complementary”>
	<article role="article" aria-live="polite" aria-atomic="true" >
		<h3 class="twitter_search"><?php echo $this->grup["ad"]; ?></h3>
		<p><?php echo $this->grup["tanim"]; ?></p>
		<hr />
		<h4>Elemanlar</h4>
		<ul>
		<?php foreach($this->Elemanlar as $eleman) echo "<li><span class=\"twitter_search\">".$eleman["ad"]."</span>(".$eleman["ens"].")</li>"; ?>
		</ul>
		<hr />
		<h4>Albümler</h4>
		<ul>
		<?php foreach($this->Albumler as $album) echo "<li>".$album["yil"]."-<span class=\"twitter_search\">".$album["ad"]."</span></li>"; ?>
		</ul>
		<hr />
	</article>
	<br class="clear" />
	<a class="tooltip">Neden bu albüm çalıyor?<span class="classic border shadow"><em>Çünkü</em>"Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported" lisanslı bedava bir albüm. Daha önemlisi PHP için bir şarkıları var.</span></a>
	<br class="clear" />
	<img src="/main/images/muzik/cover.GIF" alt="Emergent Collective One" title="Emergent Collective One" id="coverImg" />
