	<div id="filmDiv" class="hreview">
		<video id="movies" onplay="startVideo()" onended="stopTimeline()" onpause="stopTimeline()" preload="auto" controls class="item">
			<source src="<?php echo $this->film['mp4']; ?>" type='video/mp4'></source>
			<source src="<?php echo $this->film['webm']; ?>" type='video/webm'></source>
			<source src="<?php echo $this->film['ogg']; ?>" type='video/ogg'></source>
			<track src="<?php echo $this->film['desc']; ?>" kind="descriptions" srclang="en" />
			<track src="<?php echo $this->film['chap']; ?>" kind="chapters" srclang="en" />
			<track src="<?php echo $this->film['en']; ?>" kind="subtitles" srclang="en" />
			<track src="<?php echo $this->film['tr']; ?>" kind="subtitles" srclang="tr" />
			<track src="<?php echo $this->film['meta']; ?>" kind="metadata" srclang="en" />
			<img src="<?php echo $this->poster; ?>" alt="<?php echo $this->film['film_ad']; ?>" title="Görüntü oynatılamıyor. İsterseniz aşağıdaki linkten indirebilirsiniz." />
		</video>
		<p class='uyari'><b>İndir:</b>
			Kapalı Format:	<a class="url" target='_blank' href="<?php echo $this->film['mp4']; ?>">'MP4'</a> 
			Açık Format:	<a class="url" target='_blank' href="<?php echo $this->film['ogg']; ?>">'OGG'</a>
			Google Format:	<a class="url" target='_blank' href="<?php echo $this->film['webm']; ?>">'WEBM'</a>
		</p><br />
		<a target='_blank' class='panelA' title="<?php echo $this->film['film_ad']; ?>" href="<?php echo $this->href; ?>" rel="bookmark"><img class="photo" src="<?php echo $this->poster; ?>" alt="<?php echo $this->film['film_ad']; ?>"></a>
		<h3 class="fn"><?php echo $this->film["film_ad"] ?></h3>
		<p class="rating"><b>Rating:</b><span class="value"><?php echo $this->rating; ?></span>/<span class="best">10</span></p>
		<p><b>Dil:</b><?php echo $this->dil; ?></p>
		<p><b>Yıl:</b><time pubdate><?php echo $this->released; ?></time></p>
		<p class="summary"><?php echo $this->overview; ?></p>
	</div>	
	<br class="clear" />
	<h4 id="cnvHed"></h4>
	<canvas id="timeline" />
	<table>
		<thead>
			<caption>Film İstekleri</caption>
			<tr><th></th><th>Film</th><th>Oy</th></tr>
		</thead>
		<tfoot>
			<tr>
				<td><?php echo count($this->istek); ?></td>
				<td>isteğe toplam</td>
				<td><?php
					$s=0;
					function count_usr(&$item1, $key)
					{
						$s += $item1["oy"];
					}
					array_walk($this->istek, 'count_usr');
					echo $s." oy verildi.";
					//echo array_sum($this->istek); 
				?></td>
			</tr>
		</tfoot>
		<tbody>
			<?php
			$i=0;
			foreach($this->istek as $istek)
				echo "<tr><td>".++$i."</td><td>".$istek["film_ad"]."</td><td>".$istek["oy"]."</td></tr>";
			?>
		</tbody>
	</table>
</div>
<aside id="rcnt" role=”complementary”>
	<div id="uzunluk-range">
		<form>
			<label for="min">En kısa:</label>
			<input type="range" id="min" name="min" value="0" min="0" max="40" step="5" aria-orientation= "vertical" role="slider" aria-valuemin="0" aria-valuemax="40" aria-valuenow="0" aria-valuetext="0" /> 
			<!-- name değerlerini silme -->
			<br />
			<label for="max">En uzun:</label>
			<input type="range" id="max" name="max" value="45" min="5" max="45" step="5" aria-orientation= "vertical" role="slider" aria-valuemin="5" aria-valuemax="45" aria-valuenow="45" aria-valuetext="45" />
		</form>
	</div>
	<br />
	<?php if (count($this->records)): ?>
	<div id="pager">
	<?php echo $this->pages; ?>
	</div>
	<table>
	<thead>
		<tr>	
			<th class="key">
				<a class="upBlue" href="<?php echo $this->url(array('sort' => 'id','dir' => 'asc'), 'watch'); ?>"><?php echo $this->url(array('sort' => 'id','dir' => 'asc'), 'watch'); ?></a>
				Sıra
				<a class="downBlue" href="<?php echo $this->url(array('sort' => 'id','dir' => 'desc'), 'watch'); ?>"><?php echo $this->url(array('sort' => 'id','dir' => 'desc'), 'watch'); ?></a>
			</th>
		</tr>
		<tr>	
			<th class="key">
				<a class="upBlue" href="<?php echo $this->url(array('sort' => 'film_ad','dir' => 'asc'), 'watch'); ?>"><?php echo $this->url(array('sort' => 'film_ad','dir' => 'asc'), 'watch'); ?></a>
				Film
				<a class="downBlue" href="<?php echo $this->url(array('sort' => 'film_ad','dir' => 'desc'), 'watch'); ?>"><?php echo $this->url(array('sort' => 'film_ad','dir' => 'desc'), 'watch'); ?></a>
			</th>
		</tr>	
		<tr>	
			<th class="key">
				<a class="upBlue" href="<?php echo $this->url(array('sort' => 'uzunluk', 'dir'=> 'asc'), 'watch'); ?>"><?php echo $this->url(array('sort' => 'uzunluk', 'dir'=> 'asc'), 'watch'); ?></a>
				Süre
				<a class="downBlue" href="<?php echo $this->url(array('sort' => 'uzunluk', 'dir'=> 'desc'), 'watch'); ?>"><?php echo $this->url(array('sort' => 'uzunluk', 'dir'=> 'desc'), 'watch'); ?></a>
			</th>
		</tr>
	</thead>
	<tbody class="hreview">
		<?php foreach ($this->records as $r):?>
			<tr class="item">
				<td><h4 class="ui-widget ui-widget-header structured name"><?php echo $r['film_ad']; ?> (<time><?php echo $r['uzunluk']; ?></time>)</h4><a class="url" rel="self bookmark" id="<?php echo $r['id']; ?>" href="?id=<?php echo $r['id']; ?>"><img class="photo" src="<?php echo $r['poster']; ?>" alt="<?php echo $r['film_ad']; ?>" title="<?php echo $r['film_ad']; ?>" /></a></td>
			</tr>
		<?php endforeach; ?>
	</tbody>
	</table>

	<?php else: ?>
	Kayıt bulunamadı!
	<?php endif; ?> 
	<script src='/main/js/evercookie/evercookie.js'></script>
