<?php
$this->layout()->nestedLayout = 'minimal';
$this->headScript()->appendFile("http://api.recaptcha.net/js/recaptcha_ajax.js");
$this->headScript()->appendFile("/main/js/login/index.js");
$this->headScript()->appendFile("/main/js/login/slide.js");
$this->headLink()->appendStylesheet("/main/css/login/index.css");
$this->headLink()->appendStylesheet("/main/css/login/slide.css");
$this->title="Login";
?>
<section>
	<div class="blur">
		<br />
		<br />
		<form id="myspace-form" method="POST" action="/main/login/myspace">
			<fieldset>
				<legend>Myspace ile Bağlan</legend>
				<label for="myspace">E-mail:</label>
				<input type="email" name="myspace" size="23" />
				<label for="myspace_pass">Şifre:</label>
				<input type="password" name="myspace_pass" size="23" />
				<input type="submit" value="Giriş" class="bt_register" />
			</fieldset>
		</form>
		<br />
		<div class="overlay">
			<div>Sitenin neredeyse tüm sayfaları kullanıma açıktır. Sadece yönetici bölümlerine site tasarımcıları erişebilir.</div>
		</div>
	</div>
	<div id="toppanel">
		<div id="panel">
			<div class="content clearfix">
				<div class="left">
					<h1>Hoş Geldiniz</h1>
					<h2>Nasıl kayıt olurum?</h2>		
					<p class="grey">Ne yazık ki olamazsınız! Yönetici (Admin) kısmı sadece site tasarımcılarına ayrılmıştır. Sitenin geri kalan kısmı (şimdilik) herkese açıktır.</p>
					<span class="uyari"><?php echo $this->uyari ?></span>
				</div>
				<form id="login-form" method="post">
					<div class="left clearfix">
						<h1>Yönetici Girişi</h1>
						<label class="grey" for="login">İsim:</label>
						<input type="password" id="login" name="login" class="field" size="23" />
						<label class="grey" for="password">Şifre:</label>
						<input class="field" type="password" name="sifre" id="password" size="23" />
						<div class="clear"></div>
					</div>
					<div class="left">			
							<h1>Captcha Kontrol</h1>		
							<?php  echo $this->recaptcha ?>
							<input type="submit" id="giris" name="giris" value="Giriş" class="bt_login" />
					</div>
					<p class="sakla"><label for="fax">Faks (Sakın yazma):</label><input name="fax" /><input type="hidden" value="<?php echo base64_encode(time()); ?>" name="formKey"/></p>
				</form>
			</div>
		</div>
		<div class="tab">
			<ul class="login">
				<li class="left">&nbsp;</li>
				<li>Merhaba <?php echo empty($this->akraba) ? "Yabancı" : $this->akraba; ?>!</li>
				<li class="sep">|</li>
				<li id="toggle">
					<a id="open" class="open" href="#">Yönetici?</a>
					<a id="close" style="display: none;" class="close" href="#">Paneli Kapat</a>			
				</li>
				<li class="right">&nbsp;</li>
			</ul> 
		</div>
	</div>
	<div id="feedback">
		<span class="color color-1"></span>
		<span class="color color-2"></span>
		<span class="color color-3"></span>
		<span class="color color-4"></span>
		<span class="color color-5"></span>
		<div class="section">
			<h3><span class="arrow up"></span>İstek</h3>
			<p class="message">Dilek,öneri,şikayet, ne istiyorsan yaz.</p>
			<textarea></textarea>
			<a class="bt_login" href="">Submit</a>
		</div>
	</div>
</section>
<aside id="rp_list" class="rp_list">
   <ul>
		<li class="anaSayfaLI">
			<a href="<?php echo $this->url(array(), 'ana'); ?>">
				<div class="rp_div">Ana Sayfa</div>
		   </a>
		</li>
		<li class="muzikLI">
			<a href="<?php echo $this->url(array(), 'dinle'); ?>">
				<div class="rp_div">Dinle</div>
		   </a>
		</li>
		<li class="filmLI">
			<a href="<?php echo $this->url(array(), 'izle'); ?>">
				<div class="rp_div">İzle</div>
		   </a>
		</li>
		<li class="agacLI">
			<a href="<?php echo $this->url(array(), 'aile'); ?>">
				<div class="rp_div">Aile</div>
			</a>
		</li>
		<li class="kitapLI">
			<a href="<?php echo $this->url(array(), 'oku'); ?>">
				<div class="rp_div">Oku</div>
		   </a>
		</li>
		<li class="ayarlarLI">
			<a href="<?php echo $this->url(array(), 'logout'); ?>">
				<div class="rp_div">Logout</div>
			</a>
		</li>
   </ul>
</aside>
<script>	
IE6 = (navigator.appVersion.indexOf("MSIE 6.")==-1) ? false : true;
IE7 = (navigator.appVersion.indexOf("MSIE 7.")==-1) ? false : true;
IE8 = (navigator.appVersion.indexOf("MSIE 8.")==-1) ? false : true;

    var $list = $('#rp_list ul'),
		marginLeftAnimate = (IE7) ? "-450px" : "-225px",
		elems_cnt = $list.children().length;		
    $list.find('li').show().andSelf().find('.rp_div').css('margin-left','-195px');
    var d = 200;
    $list.find('li .rp_div').each(function(){
	$(this).stop().animate({'marginLeft':'-50px'},d += 100);
    });

    $list.find('li').live('mouseenter',function () {
	$(this).find('.rp_div').stop().animate({'marginLeft':marginLeftAnimate},200);})
    .live('mouseleave',function () {
	$(this).find('.rp_div').stop().animate({'marginLeft':'-50px'},200);
    });
</script>
