<?php require_once "main/Helpers/Cache/x-cache.php"; $this->tracker(); ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="tr" class="no-js"> <!--  manifest="/cache.manifest" -->
<head>
	<meta charset="UTF-8" />
	<meta content="true" name="mssmarttagspreventparsing" />
	<meta name="author" content="İbrahim Taşdemir" />
	<meta name="copyright" content="Copyright İbrahim Taşdemir 2010. All Rights Reserved." />
	<meta name="keywords" content="itsphp,ibrahim,taşdemir,ibrahim taşdemir,aile ağacı" />
	<meta name="robots" content="all" />
	<meta name="distribution" content="global" />
	<meta name="resource-type" content="document" />
	<meta name="description" content="<?php echo $this->title ?> ibrahim Taşdemir aile ağacı, kısa filmler, müzik tavsiyeleri, PHP, CSS, Javascript, jQuery, HTML, ASP.NET ile ilgili kitaplar, ipuçları..." />
	<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0;" />
	<meta name="mobileoptimized" content="0" />
	<link rel="shortcut icon" href="/main/images/favicon.ico" /> 
	<meta name="google-site-verification" content="vSA45uu-IXiT_BDv2sgitxW6fbRBcgByO_gnJNeEdxI" />
	<link rel="alternate" href="http://feeds.feedburner.com/kitap-itsphp" title="Kitap-ITSPHP" type="application/rss+xml" />
	<link rel="alternate" href="http://feeds.feedburner.com/aile-itsphp" title="Aile-ITSPHP" type="application/rss+xml" />
	<link rel="alternate" href="http://tasdemir.0fees.net/main/haber/muzik" title="Müzik-ITSPHP" type="application/rss+xml" />
	<link rel="stylesheet" media="all" href="/main/css/CSS.php" />
	<!--[if (gte IE 5.5)&(lte IE 8)]>
		<script src="/main/js/selectivizr.js"></script>
		<script src="http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE9.js">IE7_PNG_SUFFIX=".png";</script>
	<![endif]-->
	<link rel="stylesheet" media="all" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/start/jquery-ui.css" />
	<link rel="stylesheet" media="print" href="/main/css/print.css" />
	<link rel="stylesheet" media="handheld" href="/main/css/handheld.css" />
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"></script>
	<script>!window.jQuery && document.write(unescape('%3Cscript src="/main/js/jquery/jquery.min.js"%3E%3C/script%3E'))</script>
	<script src="/main/js/modernizr-1.6.min.js"></script>
	<title><?php echo $this->title ?> | ITSPHP</title>
</head>
<!--[if lt IE 7 ]> <body class="ie6"> <![endif]-->
<!--[if IE 7 ]>    <body class="ie7"> <![endif]-->
<!--[if IE 8 ]>    <body class="ie8"> <![endif]-->
<!--[if IE 9 ]>    <body class="ie9"> <![endif]-->
<!--[if gt IE 9]>  <body><![endif]-->
<!--[if !IE]><!--> <body><!--<![endif]-->
<div id="container">
	<header id="hdr" role="heading">
		<hgroup role="banner">
			<h1><a href="<?php echo $this->url(array(), 'ana'); ?>">İbrahim Taşdemir</a>'in Kişisel Ana Sayfası</h1>
			<h2><?php echo $this->h2; ?></h2>
		</hgroup>
		<a class="skip" href="#cnt">içeriği geç</a> 
		<menu class="oe_wrapper tour_1" role="menu">
			<ul id="oe_menu" class="oe_menu">
				<li <?php if($this->isAile) echo "class='selected2'" ?>><a href="<?php echo $this->url(array(), 'aile'); ?>">Aile</a>
					<div style="left:-1px;">
						<ul>
							<li class="oe_heading">Bireyler</li>
							<li><a href="<?php echo $this->url(array(), 'aile'); ?>?id=11">İbrahim Taşdemir</a></li>
							<li><a href="<?php echo $this->url(array(), 'aile'); ?>?id=10">Ömer Taşdemir</a></li>
							<li><a href="<?php echo $this->url(array(), 'aile'); ?>?id=9">Rafet Taşdemir</a></li>
							<li><a href="<?php echo $this->url(array(), 'aile'); ?>?id=60">Handan Özcan</a></li>
							<li><a href="<?php echo $this->url(array(), 'aile'); ?>">Ve diğerleri</a></li>
						</ul>
						<ul>
							<li class="oe_heading">Ekle veya Güncelle</li>
							<li><a href="<?php echo $this->url(array('page' => ''), 'form'); ?>">Yeni Ekle</a></li>
							<li><a href="<?php echo $this->url(array('page' => '11'), 'form'); ?>">İbrahim Taşdemir</a></li>
							<li><a href="<?php echo $this->url(array('page' => '10'), 'form'); ?>">Ömer Taşdemir</a></li>
							<li><a href="<?php echo $this->url(array('page' => '9'), 'form'); ?>">Rafet Taşdemir</a></li>
							<li><a href="<?php echo $this->url(array('page' => '60'), 'form'); ?>">Handan Özcan</a></li>
						</ul>
						<ul>
							<li class="oe_heading">Diğer</li>
							<li><a href="<?php echo $this->url(array(), 'harita'); ?>" > Harita</a></li>
							<li><a href="<?php echo $this->url(array(), 'agac'); ?>">Ağaç</a></li>
							<li><a href="<?php echo $this->url(array(), 'resim'); ?>">Resimler</a></li>
							<li><a href="<?php echo $this->url(array(), 'video'); ?>">Videolar</a></li>
							<li><a href="<?php echo $this->url(array(), 'galeri'); ?>" >Galeri</a><li>
						</ul>
					</div>
				</li>
				<li <?php if($this->isOku) echo "class='selected2'" ?>><a href="<?php echo $this->url(array('page' => 'programlama'), 'oku'); ?>">Oku</a>
					<div style="left:-112px;">
						<ul class="oe_full">
							<li class="oe_heading">Programlama Kitapları</li>
							<li><a href="<?php echo $this->url(array('page' => 'programlama'), 'oku'); ?>#HTML">HTML</a></li>
							<li><a href="<?php echo $this->url(array('page' => 'programlama'), 'oku'); ?>#CSS">CSS</a></li>
							<li><a href="<?php echo $this->url(array('page' => 'programlama'), 'oku'); ?>#JS">JavaScript</a></li>
							<li><a href="<?php echo $this->url(array('page' => 'programlama'), 'oku'); ?>#PHP">PHP</a></li>
							<li><a href="<?php echo $this->url(array('page' => 'programlama'), 'oku'); ?>#ASP">ASP.NET</a></li>
							<li><a href="<?php echo $this->url(array('page' => 'programlama'), 'oku'); ?>#DIGER">Diğer</a></li>
						</ul>
					</div>
				</li>
				<li <?php if($this->isHaber) echo "class='selected2'" ?>><a href="<?php echo $this->url(array(), 'feed'); ?>">Haber</a>
					<div style="left:-224px;">
						<ul class="oe_full">
							<li class="oe_heading">Beslemeler</li>
							<li><a href="<?php echo $this->url(array(), 'feed'); ?>">RSS Besleme Sayfası</a></li>
							<li><a href="http://tasdemir.0fees.net/main/haber/muzik" target="_blank" rel="nofollow">Müzik</a></li>
							<li><a href="http://feeds.feedburner.com/aile-itsphp" target="_blank" rel="nofollow">Aile</a></li>
							<li><a href="http://feeds.feedburner.com/kitap-itsphp" target="_blank" rel="nofollow">Kitap</a></li>
						</ul>
					</div>
				</li>
				<li <?php if($this->isSosyal) echo "class='selected2'" ?>><a href="<?php echo $this->url(array(), 'iletisim'); ?>">Sosyal</a>
					<div style="left:-335px;">
						<ul class="oe_full">
							<li class="oe_heading">İletişime Geçin</li>
							<li><a href="<?php echo $this->url(array(), 'iletisim'); ?>">Öneriler ve SSS</a></li>
							<li><a href="<?php echo $this->url(array(), 'forum'); ?>">Forum</a></li>
							<li><a href="<?php echo $this->url(array(), 'chat'); ?>" >Chat</a></li>
						</ul>
					</div>
				</li>
				<li <?php if($this->isMuzik) echo "class='selected2'" ?>><a href="<?php echo $this->url(array('page' => 'metal'), 'dinle'); ?>" >Müzik Dinle</a></li>
				<li <?php if($this->isFilm) echo "class='selected2'" ?>><a href="<?php echo $this->url(array(), 'watch'); ?>" >Kısa Film İzle</a></li>
				<li>
					<?php if (Zend_Auth::getInstance()->hasIdentity())  : ?>
						<a id="log" href="<?php echo $this->url(array(), 'logout'); ?>">LOGOUT</a>
					<?php else: ?>
						<a id="log" href="<?php echo $this->url(array(), 'login'); ?>">LOGIN</a>
					<?php endif; ?>
				</li>
			</ul>	
        	</menu>
		<div id="tourcontrols" class="tourcontrols">
			<p>İlk ziyaretiniz mi?</p>
			<span class="tour_button" id="activatetour">Tura başla</span>
			<div class="nav">
				<span class="tour_button" id="prevstep" style="display:none;">< Önceki</span>
				<span class="tour_button" id="nextstep" style="display:none;">Sonraki ></span>
			</div>
			<a id="restarttour" style="display:none;">Başa Dön</a>
			<a id="endtour" style="display:none;">Turu Bitir</a>
			<span class="tour_close" id="canceltour"></span>
		</div>
		<section id="hsec" class="ui-widget-header">
			<h6>Designed By İbrahim Taşdemir</h6>
			<aside id="banner2">
				Bitly:<span class="uyari" id="bitly"><?php echo getBitly(getSiteName()."main/".$this->url); ?></span> <br />
				TinyURL:<span class="uyari"><?php echo getTiny(getSiteName()."main/".$this->url); ?></span>
			</aside>
			<a href="/mobil/" class="headerButton">Mobil Sayfayı Aç</a>
		</section>
	</header>
	<div id="cnt">
		<aside id="lcnt" role=”complementary”>
			<nav id="rssTakip" role="navigation">
				<p><a target="_blank" href="http://feeds.feedburner.com/aile-itsphp" rel="alternate" type="application/rss+xml">Aile <img src="http://www.feedburner.com/fb/images/pub/feed-icon16x16.png" /></a></p><br />
				<p><a target="_blank" href="http://tasdemir.0fees.net/main/haber/muzik" rel="alternate" type="application/rss+xml">Müzik <img src="http://www.feedburner.com/fb/images/pub/feed-icon16x16.png" /></a></p><br />
				<p><a target="_blank" href="http://feeds.feedburner.com/kitap-itsphp" rel="alternate" type="application/rss+xml">Kitap <img src="http://www.feedburner.com/fb/images/pub/feed-icon16x16.png" /></a></p><br />
			</nav>	
			<?php echo $this->appreciate(); ?>
			<details open>
				<summary class="sidetit_l ui-widget ui-widget-header tour_3"><span class="details-close ui-icon ui-icon-closethick">X</span>Yapıldı</summary>
				<p>
		<img alt="Apache-2.2.15" title="Apache" src="/main/images/apache.png" width="32" height="32" />
		<img alt="CouchDB-1.0.1" title="CouchDB" src="/main/images/couchdb.png" width="32" height="32" />
		<img alt="Doctrine-1.2.3" title="Doctrine" src="/main/images/doctrine.png" width="32" height="32" />
		<img alt="FirePHP-0.3.2rc6" title="FirePHP" src="/main/images/fp.png" width="32" height="32" />
		<img alt="GitHub" title="GitHub" src="/main/images/git.png" width="32" height="32" />
		<img alt="HTML5" title="HTML5" src="http://www.w3.org/html/logo/downloads/HTML5_Badge_32.png" width="32" height="32" />
		<img alt="jQuery-1.4.2" title="jQuery,jQuery UI,jQuery Mobile" src="/main/images/jquery.png" width="32" height="32" />
		<img alt="MySQL-5.1.41" title="MySQL" src="/main/images/mysql.png" width="32" height="32" />
		<img alt="Modernizr-1.6" title="Modernizr" src="/main/images/modernizr.png" width="32" height="32" />
		<img alt="PHP-5.3" title="PHP:HyperText Processor" src="/main/images/php.png" width="32" height="32" />
		<img alt="SimplePIE-1.2" title="SimplePIE" src="/main/images/simplepie.png" width="32" height="32" />
		<img alt="Smarty-2.6.26" title="Smarty" src="/main/images/smarty.jpg" width="32" height="32" />
		<img alt="Zend Framework-1.10.8" title="Zend Framework" src="/main/images/zf.png" width="32" height="32" />
				</p>
			</details>
			<details id="browser" open>
				<summary class="sidetit_l ui-widget ui-widget-header tour_4"><span class="details-close ui-icon ui-icon-closethick">X</span>Test Edildi</summary>
				<a target="_blank" rel="nofollow" href="http://www.microsoft.com/windows/internet-explorer/worldwide-sites.aspx" title="Internet Explorer 8+" ><div id="ie">Internet Explorer 8+</div></a>
				<a target="_blank" rel="nofollow" href="http://getfirefox.com/" title="Firefox" ><div id="firefox">Firefox</div></a>
				<a target="_blank" rel="nofollow" href="http://www.opera.com/" title="Opera" ><div id="opera">Opera</div></a>
				<a target="_blank" rel="nofollow" href="http://www.google.com/chrome" title="Chrome" ><div id="chrome">Chrome</div></a>
				<a target="_blank" rel="nofollow" href="http://www.chromium.org/Home" title="Chromium" ><div id="chromium">Chromium</div></a>
				<a target="_blank" rel="nofollow" href="http://www.apple.com/safari/download/" title="Safari" ><div id="safari">Safari</div></a>
				<a target="_blank" rel="nofollow" href="http://www.seamonkey-project.org/releases/" title="Seamonkey" ><div id="seamonkey">Seamonkey</div></a>
				<a target="_blank" rel="nofollow" href="http://www.flock.com/" title="Flock" ><div id="flock">Flock</div></a>
			<br class="clear" />
			</details>
			<details open>
				<summary class="sidetit_l ui-widget ui-widget-header tour_5"><span class="details-close ui-icon ui-icon-closethick">X</span>Onaylandı</summary>
				<p><a target="_blank" rel="nofollow" href="http://www.achecker.ca/checker/index.php?uri=referer&amp;gid=WCAG1-AAA"><img height="32" width="88" src="http://www.w3.org/WAI/wcag1AAA" alt="Level Triple-A conformance icon, W3C-WAI Web Content Accessibility Guidelines 1.0" title="Level Triple-A conformance icon, W3C-WAI Web Content Accessibility Guidelines 1.0"></a><a target="_blank" rel="nofollow" href="http://jigsaw.w3.org/css-validator/check/referer"><img src="http://jigsaw.w3.org/css-validator/images/vcss-blue" alt="Valid CSS!" title="Valid CSS!" width="88"  height="31" /></a><img src="http://www.boogdesign.com/images/buttons/smf_green.png" alt="Micro Format" title="Micro Format"/></p>
			</details>
			<details open>
				<summary class="sidetit_l ui-widget ui-widget-header tour_6"><span class="details-close ui-icon ui-icon-closethick">X</span>Paylaşıldı</summary>
				<?php echo $this->social(); ?>
				<br class="clear" />
				<script src="http://twittercounter.com/embed/?username=itasdemir86&style=bird"></script>
				<br class="clear" />
			</details>
			<?php echo $this->twitter(); ?>
			<details open>
				<summary class="sidetit_l ui-widget ui-widget-header"><span class="details-close ui-icon ui-icon-closethick">X</span>Yönetildi</summary>
				<nav id="adminlink" class="lslink" role="navigation">
					<ul>
						<li><a id="adsense" href="<?php echo $this->url(array(), 'adsense'); ?>">Adsense Kazanç</a></li>
						<li><a id="midware" href="<?php echo $this->url(array(), 'midware'); ?>">Midware Ayarlar</a></li>
						<li><a id="sunucu" href="<?php echo $this->url(array(), 'sunucu'); ?>">Sunucu Ayarlar</a></li>
						<li><a id="dosya" href="<?php echo $this->url(array(), 'dosya'); ?>">Dosya Yönetimi</a></li>
						<li><a id="abuse" href="<?php echo $this->url(array(), 'abuse'); ?>">Hacker Kontrol</a></li>
						<li><a id="admin" href="<?php echo $this->url(array(), 'admin'); ?>">Admin Ayarları</a></li>
						<li><a id="fulltext" href="<?php echo $this->url(array(), 'fulltext'); ?>">Arama Ayarlar</a></li>
						<li><a id="stats" href="<?php echo $this->url(array(), 'stats'); ?>">Ziyaretçiler</a></li>
						<li><a id="jstest" href="<?php echo $this->url(array(), 'js'); ?>">JS Kontrol</a></li>
						<li><a id="hata" href="<?php echo $this->url(array(), 'hata'); ?>">Hatalar</a></li>
						<li><a id="shell" href="<?php echo $this->url(array(), 'shell'); ?>">Shell</a></li>
						<li><a id="api" href="<?php echo $this->url(array(), 'api'); ?>">Api</a></li>
						<li><a id="hiz" href="<?php echo $this->url(array(), 'hiz'); ?>">Hız</a></li>
					</ul>
				</nav>
			</details>
			<?php echo $this->lastfm(); ?>
			<?php echo $this->git(); ?>
		</aside>

		<div id="ccnt" role="main">

			<?php flush(); echo $this->layout()->content; flush(); ?>

			<br class="clear" />
			<details id="mailLink" class="rslink" open>
				<summary class="sidetit_r ui-widget ui-widget-header tour_7">E-Posta Haber<span class="details-close ui-icon ui-icon-closethick">X</span></summary>
				<a href="http://eepurl.com/ZGN6" title="Haber bültenine kaydol" target="_blank" rel="nofollow" class="jqueryButton translate"><img class="transition" src="/main/images/mail_add.png" alt="Kaydol" /></a>
				<a href="http://0fees.us2.list-manage.com/unsubscribe?u=bb24c290b5d488724f4ce0b31&amp;id=d138cafbda" title="Kaydımı Sil" target="_blank" rel="nofollow" class="jqueryButton translate2"><img class="transition" src="/main/images/mail_delete.png" alt="Sil" /></a>
			</details>
			<details id="jsPromote" open>
				<summary class="sidetit_r ui-widget ui-widget-header tour_8">Interneti Geliştir<span class="details-close ui-icon ui-icon-closethick">X</span></summary>
				<a href="https://developer.mozilla.org/en/JavaScript" title="JavaScript Reference, JavaScript Guide, JavaScript API, JS API, JS Guide, JS Reference, Learn JS, JS Documentation" target="_blank"><img src="http://static.jsconf.us/promotejsvs.png" alt="JavaScript Reference, JavaScript Guide, JavaScript API, JS API, JS Guide, JS Reference, Learn JS, JS Documentation"/></a>
			</details>
			<?php echo $this->stack(); ?>
		</aside>
		<br class="clear"/>
	</div>
	<footer role="contentinfo" class="tour_10">
		<section>
			<small>&copy; 2009 Stylissimo. Tüm hakları saklıdır.</small>
			<a id="dryicon" target="_blank" rel="nofollow" href="http://dryicons.com/" title="Stylissimo Tasarım ve resimler DryIcons.com tarafından sağlanmıştır">Tasarım ve resimler DryIcons tarafından sağlanmıştır</a>
		</section>
		<section id="foot_two">
			<article> 
				<div class="cont">
					<h5 class="fire">İbrahim Taşdemir</h5><br />
					<img id="footImg" src="<?php echo getResim(11); ?>" alt="İbrahim Taşdemir" />
					<p>
						<a href="http://www.delicious.com/tasdemiribrahim" target="_blank" rel="nofollow me"><img src="/main/images/delicious.png" alt="Delicious" title="Delicious" /></a>
						<a href="http://www.facebook.com/tasdemiribrahim" target="_blank" rel="nofollow me"><img src="/main/images/facebook.png" alt="Facebook" title="Facebook" /></a>
						<a href="http://www.flickr.com/tasdemiribrahim" target="_blank" rel="nofollow me"><img src="/main/images/flickr.png" alt="Flickr" title="Flickr" /></a>
						<a href="http://www.friendfeed.com/tasdemiribrahim" target="_blank" rel="nofollow me"><img src="/main/images/friendfeed.png" alt="Friendfeed" title="Friendfeed" /></a>
						<a href="http://www.lastfm.com.tr/user/tasdemiribrahim" target="_blank" rel="nofollow me"><img src="/main/images/lastfm.png" alt="Last Fm" title="Last Fm" /></a>
						<a href="http://www.twitter.com/itasdemir86" target="_blank" rel="nofollow me"><img src="/main/images/twitter.png" alt="Twitter" title="Twitter" /></a>
					</p>
				</div>
				<div class="cont" id="lastfmrecords"><h5 class="fire">Dinliyor</h5><br /></div>
				<div class="cont" id="fb-root"></div>
				<!-- FBML <fb:fan profile_id="140067416030204" stream="false" header="true" ></fb:fan> FBML -->
				<br class="clear" />
			</article>
		</section>
		<section id="foot_three" class="ui-widget-header tour_11">
			<a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/"><img alt="Creative Commons License" src="http://i.creativecommons.org/l/by-sa/3.0/80x15.png" /><!--88x31 --></a>Bu site <a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/">Creative Commons Attribution-ShareAlike 3.0 Unported Lisans</a> tarafından korunuyor. &copy; 2010,<a href="mailto:tasdemiribrahim@hotmail.com.tr" rel="me">İbrahim Taşdemir</a>
		</section>
	</footer>
</div>
<div id="growl"></div>
<div class="progress sakla" ></div>
<form class="sakla">
	<label for="fax">Faks (Sakın yazma):</label><input type="text" id="fax" />
	<input type="hidden" value="<?php echo base64_encode(time()); ?>" name="formKey" id="formKey" />
</form>
<div id="bounceBox" class="sakla"><div id="player"><div id='tweets'></div><img id="loadingTweets" src="/main/images/aile/loading.gif" alt="Yükleniyor" /></div><div id="bounceKapat" class="escBlue"></div></div>
<?php echo $this->breadcrumb(); ?>
<script>
//<![CDATA[<!--
$(window).error(function(msg, urls, line){
	$.ajax({
		type: 'GET',
		url: '/main/Helpers/ErrorHandlerJS.php',
		data: 'msg='+msg.toString()+'&url='+urls+'&line='+line+'&parent='+document.location.href+'&agent='+navigator.appName+navigator.appVersion
	});
});

var _gaq = _gaq || [];
_gaq.push(["_setAccount", "UA-17794118-2"]);
_gaq.push(["_trackPageview"]);

(function() {
var ga = document.createElement("script"); ga.type = "text/javascript"; ga.async = true;
ga.src = ("https:" == document.location.protocol ? "https://ssl" : "http://www") + ".google-analytics.com/ga.js";
var s = document.getElementsByTagName("script")[0]; s.parentNode.insertBefore(ga, s);
})();
//-->//]]>
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.8/jquery-ui.min.js"></script>
<script async src="http://ajax.microsoft.com/ajax/jquery.validate/1.7/jquery.validate.min.js"></script>
<script src="http://plugins.jquery.com/files/jquery.cookie.js.txt"></script>
<script async src="http://delicious-button.googlecode.com/files/jquery.delicious-button-1.0.min.js"></script>
<script async src="/main/js/AjaxUpload-3.5.js"></script>
<script src="/main/js/JS.php"></script>
<script src="/main/js/<?php echo $this->script.".js?".date("Ymdhis"); ?>"></script>
<?php finish_caching(); ?> 
</body>
</html>
