<details class="hataSayfa"><summary>
	<?php if ('404' == $this->errCode): ?>
		<div id="rocket"></div><hgroup><h1>Sayfa Yok</h1><h2>"Houston sayfayla bağlantıyı kaybettik"</h2></hgroup>
	<?php endif ?>
	<?php if ('500' == $this->errCode): ?>
		<h1>Sunucu icinde bir hata olu&#351;tu ve sunucu talebinize hizmet vermekte ba&#351;ar&#305;l&#305; olamad&#305;.Ya sunucuya cok yuklenildi, ya da CGI betiklerinde hata belirdi.</h1>
	<?php endif;
	if ('development' == APPLICATION_ENV): ?>
		<div id="error-data">
			<h3>Exception message:</h3>
			<pre><?php echo $this->exception->getMessage(); ?></pre>
			<h3>Stack trace:</h3>
			<pre><?php echo $this->exception->getTraceAsString() ?></pre>
			<h3>Request method:</h3>
			<pre><?php echo $this->request->getMethod(); ?></pre>
			<h3>Request parameters:</h3>
			<?php Zend_Debug::dump($this->request->getParams()); ?>
			<h3>Server environment:</h3>
			<?php Zend_Debug::dump($this->request->getServer()); ?>
			<h3>System environment:</h3>
			<?php Zend_Debug::dump($this->request->getEnv()); ?>
		</div>
	<?php endif ?>
  
</summary></details>
