<section>
	<div class="blur">
		<br />
		<form id="aile-form" method="POST">
			<fieldset>
			<legend>Web ID ile Bağlan</legend>
				<div id="loginWindow">
					<div id="loginWindowInner" class="rounded">
						<div id="idBoxBgWrapper">
							<div id="idBoxBg">Tanım dosyanızı buraya bırakın...</div>
							<div id="idCardSrc">
								<div class="idCard rounded">
									<div class="idCardLeft"><img alt="WebID" src="" width="85"/></div>
									<div class="idCardRight">
										<ul class="idCardValues"></ul>
									</div>
								</div>
							</div>
						</div>
						<div id="idBox" class="rounded"></div>
						<div id="pinBox">
							<label for="txtPin">PIN:</label>
							<input type="password" name="pin" id="txtPin" class="rounded" maxlength="4" />
							<div class="clear"></div>
						</div>
						<div id="txtMain">
							<p>WebID dosyanızı sürükleyip bırakın ve PIN kodunuzu girin</p>
						</div>
					</div>
				</div>
			</fieldset>
		</form>
		<br />
		<fieldset>
			<legend>Twitter ile Bağlan</legend>
			<?php echo $this->twitter ?>
		</fieldset>
		<br />
		<fieldset>
			<legend>Facebook ile Bağlan</legend>
	 		<iframe src='http://www.facebook.com/plugins/registration.php?
		                client_id=<?php echo FACEBOOK_APP_ID; ?>&
		                redirect_uri=<?php echo getSiteName()."main/login"; ?>&
		                fields=[
		                {"name":"name"},
		                {"name":"email"},
		                {"name":"password"},
		                {"name":"gender"},
		                {"name":"birthday"},
		                {"name":"captcha"},
		                {"name":"phone", "description":"Phone Number", "type":"text"}
		                ]'
		                scrolling="auto" frameborder="no" style="border:none" allowTransparency="true" height="600">
		        </iframe>
			<span class="uyari"><?php echo $this->fbhata ?></span>
		</fieldset>
		<br />
		<form id="myspace-form" method="POST">
			<fieldset>
				<legend>Myspace ile Bağlan</legend>
				<label for="myspace">E-mail:</label>
				<input type="email" id="myspace" name="myspace" size="23" />
				<label for="myspace_pass">Şifre:</label>
				<input type="password" id="myspace_pass" name="myspace_pass" size="23" />
				<input type="submit" value="Giriş" class="bt_register" />
			</fieldset>
		</form>
		<br />
		<div class="overlay">
			<div>Sitenin neredeyse tüm sayfaları kullanıma açıktır. Sadece yönetici bölümlerine site tasarımcıları erişebilir.</div>
		</div>
	</div>
	<div id="toppanel">
		<div id="panel">
			<div class="content clearfix">
				<div class="left">
					<h1>Hoş Geldiniz</h1>
					<h2>Nasıl kayıt olurum?</h2>		
					<p class="grey">Ne yazık ki olamazsınız! Yönetici (Admin) kısmı sadece site tasarımcılarına ayrılmıştır. Sitenin geri kalan kısmı (şimdilik) herkese açıktır.</p>
					<span class="uyari"><?php echo $this->uyari ?></span>
				</div>
				<form id="login-form" method="post">
					<div class="left clearfix">
						<h1>Yönetici Girişi</h1>
						<label class="grey" for="login">İsim:</label>
						<input type="password" id="login" name="login" class="field" size="23" />
						<label class="grey" for="password">Şifre:</label>
						<input class="field" type="password" name="sifre" id="password" size="23" />
						<div class="clear"></div>
					</div>
					<div class="left">			
							<h1>Captcha Kontrol</h1>		
							<?php  echo $this->recaptcha ?>
							<input type="submit" id="giris" name="giris" value="Giriş" class="bt_login" />
					</div>
				</form>
			</div>
		</div>
		<div class="tab">
			<ul class="login">
				<li class="left">&nbsp;</li>
				<li>Merhaba <?php echo empty($this->akraba) ? "Yabancı" : $this->akraba; ?>!</li>
				<li class="sep">|</li>
				<li id="toggle">
					<a id="open" class="open" href="#">Yönetici?</a>
					<a id="close" style="display: none;" class="close" href="#">Paneli Kapat</a>			
				</li>
				<li class="right">&nbsp;</li>
			</ul> 
		</div>
	</div>

	<div id="feedback">
		<span class="color color-1"></span>
		<span class="color color-2"></span>
		<span class="color color-3"></span>
		<span class="color color-4"></span>
		<span class="color color-5"></span>
		<div class="section">
			<h3><span class="arrow up"></span>İstek</h3>
			<p class="message">Dilek,öneri,şikayet, ne istiyorsan yaz.</p>
			<textarea></textarea>
			<a class="bt_login" href="">Submit</a>
		</div>
	</div>

</section>
