<div id="forumPage">
	<header class="headingSection">
		<h3><?php echo $this->post["permalink"]; ?></h3>
		<h4><?php echo $this->post["content"]; ?></h4>
		<div id="uyari" class="uyari"></div>
	</header>
	<section class="sssSection">
			<table>
				<thead><tr><th>Mesaj</th><th>Tarih</th><th>Yazar</th></tr></thead>
				<tbody>
				<?php 
					foreach($this->cevaplar as $cevap)
						echo '<tr><td>'.$cevap["content"].'</td><td>'.$cevap["date"].'</td><td>'.$cevap["author"].'</td></tr>';
				?>
				</tbody>				
			</table>  
			<br /><br />
			<h5 class="ui-widget ui-widget-header">Cevap Yaz</h5>
			<form>
				<input type="hidden" id="permalink" name="permalink" value="<?php echo $this->post["id"]; ?>" />
				<label for="author">Yazar:</label><input class="name" id="author" name="author" placeholder="Adınız" required aria-required size="30" />
				<label for="mesaj">Mesaj:</label>
				<textarea name="mesaj" id="mesaj" rows="8" cols="70" required aria-required maxlength="500" ></textarea>
				<br />
				<div class="captcha_wrap border sakla">
					Sıralamak için sürükle
					<ul>
						<li class="shadow">1</li>
						<li class="shadow">2</li>
						<li class="shadow">3</li>
						<li class="shadow">4</li>
						<li class="shadow">5</li>
						<li class="shadow">6</li>
					</ul>
				</div>
				<input type="submit" class="bonBonButton xs morph pink glass" value="Cevabı Gönder" />
			</form>
	</section>
</div> 
</div>

<aside id="rcnt" role=”complementary”>
	<h3 class="ui-widget ui-widget-header">Forumda Konuşun</h3>
	<div id="resultsDiv"><?php
	foreach ($this->forum as $row)
		echo '<p><a href="?id='.$row['id'].'" id="'.$row['id'].'" rel="tag">'.$row['permalink'].'</a></p><time pubdate>'.$row['date'].'</time><span class="forum_author">'.$row['author'].'</span><br class="clear" />';
	?>
	</div>
	<form>
		<h4 class="sidetit_r ui-widget ui-widget-header">Yeni Konu</h4>
		<label for="input_title">Başlık:</label><input class="suggest" id="input_title" name="input_title" placeholder="Başlık" required aria-required size="20" />
		<label for="input_author">Yazar:</label><input class="name" id="input_author" name="input_author" placeholder="Adınız" required aria-required size="30" />
		<label for="input_mesaj">Mesaj:</label>
		<textarea name="input_mesaj" id="input_mesaj" rows="8" cols="70" required aria-required maxlength="500" ></textarea>
		<br /><div class="captcha_wrap border sakla">
			Sıralamak için sürükle
			<ul>
				<li class="shadow">1</li>
				<li class="shadow">2</li> 
				<li class="shadow">3</li>
				<li class="shadow">4</li>
				<li class="shadow">5</li>
				<li class="shadow">6</li>
			</ul>
		</div>
		<input type="submit" class="bonBonButton xs morph pink glass" value="Konuyu Gönder" />
	</form>
