<nav role="navigation">
	<ul id="skip">
		<li><a href="#tablo-anchor">TABLOYA GİT</a></li>
		<li><a href="#takvim-anchor">TAKVİME GİT</a></li>
	</ul>		
</nav>
<div id="chart_div"></div>
<script src="http://www.google.com/jsapi"></script>
<script>
	google.load("visualization", "1", {packages:["orgchart"]});
	google.setOnLoadCallback(drawChart);
	function drawChart() {
		var data = new google.visualization.DataTable();
		data.addColumn("string", "akrabaAd");
		data.addColumn("string", "ebeveyn");
		var resim=Array();
		<?php
			foreach ($this->aileListe as $row)
			{
				$liste[$row['aileID']]=$row['aileAd'];
				$ebeveyn[$row['aileID']]=$row['ebeveynID'];
				$resim[$row['aileID']]=getResim($row['aileID']);
				echo "resim[".$row['aileID']."]='".$resim[$row['aileID']]."';\n\r";
			}
			while(list($key,$value)=each($liste))
			{
				echo "data.addRow(['<img src=\"$resim[$key]\" alt=\"$key\" />$value','";
				echo $ebeveyn[$key]==0 ? "" : "<img src=\"".$resim[$ebeveyn[$key]]."\" alt=\"$ebeveyn[$key]\" />".$liste[$ebeveyn[$key]];
				echo "']);\n\r";
			}
		?>
		var chart = new google.visualization.OrgChart(document.getElementById("chart_div"));
		chart.draw(data, {allowHtml:true,allowCollapse:true,nodeClass:"orgChartNode",selectedNodeClass:"orgChartNodeSel"});
	}
</script>
<br class="clear" />
<h3 class="ui-widget ui-widget-header">Aile Tablo</h3>
<a id="tablo-anchor" class="accessibility">Tablo</a>
<table id="datagrid" class="display">
	<thead><tr><th> Resim </th><th> ID </th><th> İsim </th><th> Ebeveyn </th><th> Özgeçmiş </th><th> Doğum </th><th> Ölüm </th><th> Eşi </th><th> Adres </th><th> TEL </th><th> Mail </th><th> MSN </th><th> Twitter </th></tr></thead>
	<tbody>
	<?php
		foreach ($this->aile as $row)
		{
			$veri=substr($row['Detay']["aileTanim"], 0,100);
			echo "<tr class='".($row['Detay']["aileOlum"]=="0000-00-00" ? ($row['Detay']["aileBireyEs"]=="" ? "gradeX" : "gradeA") : "gradeU")."'><td><img width='100' height='150' src='".$resim[$row['aileID']]."' alt='".$row['aileAd']."'></td><td>".$row['aileID']."</td><td>".$row['aileAd']."</td><td>".$ebeveyn[$row['aileID']];
			echo "-".$liste[$ebeveyn[$row['aileID']]]."</td><td>".substr($veri,0,strrpos($veri, " "))."...</td><td>".$row['Detay']["aileDogum"]."</td><td>".$row['Detay']["aileOlum"];
			echo "</td><td>".$row['Detay']["aileBireyEs"]."</td><td>".$row['Detay']["aileBireyAdres"]."</td><td>".$row['Detay']["aileBireyTel"]."</td><td>".$row['Detay']["aileBireyMail"]."</td><td>".$row['Detay']["aileBireyMSN"]."</td><td>".$row['Detay']["aileBireyTwitter"];
			echo "</td></tr>\n";
		}
	?>
	</tbody>
</table>
<br class="clear" />
<h3 class="ui-widget ui-widget-header">Doğum Günleri ve Ölüm Yıldönümleri</h3>
<a id="takvim-anchor" class="accessibility">Takvim</a>
<div id="calendar_wrapper" style="height:500px"></div>
</div>

<aside id="rcnt" role=”complementary”>
	<div id="liste">
		<h5 class="ui-widget ui-widget-header ui-corner-all">Aile Ağacı</h5>
		<ul>
		<?php
			aileListeDoldur($liste,$ebeveyn,0);
			function aileListeDoldur($liste,$ebeveyn,$aileArray)
			{
				$aileArray=array_keys($ebeveyn,$aileArray);
				foreach($aileArray as $value)
				{
					$ulEkle=array_keys($ebeveyn,$value);
					echo "\n\r<li>".$liste[$value];
					if($ulEkle)	
					{	
						echo "<ul>";
						aileListeDoldur($liste,$ebeveyn,$value);
						echo "</ul></li>";
					}
					else echo "</li>";
				}
			}
		?>
		</ul>
	</div>
