<form id="yeniAileBireyForm" method="post">
	<input type="hidden" id="aileBireyIDHidden" name="aileBireyIDHidden" value="<?php echo $this->guncelle ?>" />
	<?php if($this->guncelle): ?>
		<h3 class="ui-widget ui-widget-header">Güncelleme Formu</h3>
	<?php else: ?>
		<h3 class="ui-widget ui-widget-header">Kaydetme Formu</h3>
	<?php endif; ?>
	<br />
	<p class="mod"><label for="aileBireyAd" title="Doldurulması zorunludur">İsim*:</label><input class="name" id="aileBireyAd" <?php if($this->guncelle) echo "disabled value='".$this->aileAd."'" ?> required aria-required /></p>
	<p class="mod"><label for="aileBireyEbeveyn" title="Doldurulması zorunludur">Ebeveyn*:</label>
	<select id="aileBireyEbeveyn" required aria-required>
	<?php 
		if($this->ebeveynAd)
			echo "<option value=".$this->ebeveynAd[0]['aileID']." id=".$this->ebeveynAd[0]['aileID'].">".$this->ebeveynAd[0]['aileID']."-".$this->ebeveynAd[0]['aileAd']."</option>";
		else
		{
			echo "<option value=''>Ebeveyn Seç</option>";
			foreach($this->aileListe as $row)
				echo "<option value=".$row['aileID']." id=".$row['aileID'].">".$row['aileID']."-".$row['aileAd']."</option>";
		}
	?>
	</select></p>
	<p class="mod"><label for="aileBireyDogum" title="Doldurulması zorunludur">Doğum*:</label><input type="date" id="aileBireyDogum" <?php if($this->guncelle) echo "disabled value='".$this->aileBirey['aileDogum']."'"; else echo "value=''"; ?> required aria-required /></p>
	<p class="mod"><label for="aileBireyOlum">Ölüm:</label><input type="date" id="aileBireyOlum" value="<?php echo $this->aileBirey['aileOlum'] ?>" /></p>
	<p class="mod"><label for="aileBireyEs">Eşi:</label><input id="aileBireyEs" value="<?php echo $this->aileBirey['aileBireyEs'] ?>" /></p>
	<p class="mod"><label for="aileBireyTanim" class="radial daire" title="Doldurulması zorunludur">Öz Geçmiş*:</label><textarea id="aileBireyTanim" rows="13" required maxlength="500"><?php echo $this->aileBirey['aileTanim'] ?></textarea></p><br />
	<p class="mod"><label for="aileBireyAdres" class="radial daire">Adres:</label><textarea id="aileBireyAdres" rows="13" maxlength="500" ><?php echo $this->aileBirey['aileBireyAdres'] ?></textarea></p><br />
	<p class="mod"><label for="aileBireyMail">E-Mail:</label><input type="email" id="aileBireyMail" value="<?php echo $this->aileBirey['aileBireyMail'] ?>" /></p>
	<p class="mod"><label for="aileBireyTel">Tel:</label><input type="tel" id="aileBireyTel" value="<?php echo $this->aileBirey['aileBireyTel'] ?>" /></p>
	<p class="mod"><label for="aileBireyMSN">MSN:</label><input type="email" id="aileBireyMSN" value="<?php echo $this->aileBirey['aileBireyMSN'] ?>" /></p>
	<p class="mod"><label for="aileBireyTwitter">Twitter:</label> http://twitter.com/<input id="aileBireyTwitter" value="<?php echo $this->aileBirey['aileBireyTwitter'] ?>" /></p>
	<p class="mod"><label for="aileBireyFlickr"><a href="http://idgettr.com/" target="_blank" rel="nofollow" title="Flickr ID 'nizi alın">FlickrID?</a>:</label><input id="aileBireyFlickr" value="<?php echo $this->aileBirey['aileBireyFlickr'] ?>" /></p>
	<p class="mod">
		<?php if ($this->guncelle): ?>
			<a href="#" id="aileBireyGuncelle" class="boubleButton blue aileKayGun">Güncelle</a>
		<?php else: ?>
			<a href="#" id="aileBireyKaydet" class="boubleButton blue aileKayGun ">Kaydet</a>
		<?php endif; ?>
		<span id="uyari" class="uyari"></span>
	</p>
</form>
</div>

<aside id="rcnt" role=”complementary”>
	<?php if($this->guncelle): ?>
		<h3 class="ui-widget ui-widget-header"><?php echo $this->aileAd; ?></h3>
		<img width="100%" src="<?php echo getResim($this->guncelle); ?>" alt="<?php echo $this->guncelle."-".$this->aileAd; ?>" title="<?php echo  $this->guncelle."-".$this->aileAd; ?>" />
		<p>Güncellemede bireyin ismi ve ebeveyni değiştirilemez!</p>
	<?php else: ?>
		<p>Yeni kayıt yaparken isim, ebeveyn, doğum ve öz geçmiş doldurulmalıdır.Ebeveyn olarak dede, büyük anne değil baba veya anneyi seçin.</p>
	<?php endif; ?>
	<br />
	<h3 class="sidetit_r ui-widget ui-widget-header">Taşdemir Ailesi</h3>
	<div class="image_carousel">
		<a class="upBlue" id="foo_prev" href="#">Geri</a>
		<a class="downBlue" id="foo_next" href="#">İleri</a>
		<nav role="navigation" id="FS_controls"></nav> 
		<br class="clear" />
		<div id="foo">
			<?php
				foreach ($this->aileListe as $row)
					echo '<img src="'.getResim($row['aileID']).'" alt="'.$row['aileID']."-".$row['aileAd'].'" title="'.$row['aileID']."-".$row['aileAd'].'" width="145" height="145" />';
			?>
		</div>
	</div>
