<form id="yabf" method="post">
	<?php if($this->guncelle): ?>
		<h3 class="ui-widget ui-widget-header"><?php echo $this->ebeveynAd[0]['ad'] ?> çocuğu <?php echo $this->aileBirey['dogum'] ?> doğumlu <?php echo $this->ad ?></h3>
		<input type="hidden" name="aidh" value="<?php echo $this->guncelle ?>" />
	<?php else: ?>
		<h3 class="ui-widget ui-widget-header">Kaydetme Formu</h3>
	<?php endif; ?>
	<br />
	<p>
		<?php if(!$this->guncelle) { ?>
		<label for="ybad" title="Doldurulması zorunludur" class="radial daire">İsim*:</label>
		<input class="name" name="ybad" required aria-required />
	</p>
	<p>
		<label for="ybe" title="Doldurulması zorunludur" class="radial daire">Ebeveyn*:</label>
		<select name="ybe" required aria-required>
			<option value=''>Ebeveyn Seç</option>
			<?php 
				foreach($this->aileListe as $row)
					echo "<option value=".$row['id']." id=".$row['id'].">".$row['id']."-".$row['ad']."</option>";
			?>
		</select>
	</p>
	<p>
		<label for="ybd" title="Doldurulması zorunludur" class="radial daire">Doğum*:</label>
		<input type="date" name="ybd" required aria-required />
		<?php } ?>
	</p>
	<p>
		<label for="ybo">Ölüm:</label>
		<input type="date" name="ybo" value="<?php echo $this->aileBirey['olum'] ?>" />
	</p>
	<p>
		<label for="ybes">Eşi:</label>
		<input name="ybes" value="<?php echo $this->aileBirey['es'] ?>" />
	</p>
	<p>
		<label for="ybt" class="radial daire" title="Doldurulması zorunludur">Öz Geçmiş*:</label>
		<textarea name="ybt" rows="5" required maxlength="500"><?php echo $this->aileBirey['tanim'] ?></textarea>
	</p>
	<br />
	<p>
		<label for="ybadres">Adres:</label>
		<textarea name="ybadres" rows="5" maxlength="500" ><?php echo $this->aileBirey['adres'] ?></textarea>
	</p>
	<br />
	<p>
		<label for="ybmail">E-Mail:</label>
		<input type="email" name="ybmail" value="<?php echo $this->aileBirey['mail'] ?>" />
	</p>
	<p>
		<label for="ybtel">Tel:</label>
		<input type="tel" name="ybt" value="<?php echo $this->aileBirey['tel'] ?>" />
	</p>
	<p>
		<label for="ybtwit">Twitter:</label> http://twitter.com/
		<input name="ybtwit" id="ybtwit" value="<?php echo $this->aileBirey['twitter'] ?>" />
	</p>
	<p>
		<label for="ybflic"><a href="http://idgettr.com/" target="_blank" rel="nofollow" title="Flickr ID 'nizi alın">FlickrID?</a>:</label>
		<input name="ybflic" value="<?php echo $this->aileBirey['flickr'] ?>" />
	</p>
	<p>
		<input type="submit" class="boubleButton blue" name="<?php echo $this->guncelle ? 'ybgun' : ' ybkay' ?>" value="<?php echo $this->guncelle ? 'Güncelle' : ' Kaydet' ?>" />
	</p>
</form>
</div>

<aside id="rcnt" role=”complementary”>
	<?php echo $this->ara(); ?>
	<?php if($this->guncelle): ?>
		<h3 class="ui-widget ui-widget-header"><?php echo $this->ad; ?></h3>
		<img width="100%" src="<?php echo getResim($this->guncelle); ?>" alt="<?php echo $this->guncelle."-".$this->ad; ?>" title="<?php echo  $this->guncelle."-".$this->ad; ?>" />
		<p>Güncellemede bireyin ismi, doğum tarihi ve ebeveyni değiştirilemez!</p>
	<?php endif; ?>
	<br />
	<h3 class="st_r ui-widget ui-widget-header">Taşdemir Ailesi</h3>
	<div class="image_carousel">
		<a class="upBlue" id="foo_prev" href="#">Geri</a>
		<a class="downBlue" id="foo_next" href="#">İleri</a>
		<nav role="navigation" id="FS_controls"></nav> 
		<br class="clear" />
		<div id="foo">
			<?php
				foreach ($this->aileListe as $row)
					echo '<img src="'.getResim($row['id']).'" alt="'.$row['id']."-".$row['ad'].'" title="'.$row['id']."-".$row['ad'].'" width="90%" height="145" />';
			?>
		</div>
	</div>
