<style>
	@import "http://jquery.bassistance.de/treeview/jquery.treeview.css";
</style>
<article id="aadd" class="vcard" itemscope itemtype="http://tasdemir.0fees.net/Birey" aria-live="polite" aria-atomic="true" > 
	<img class="photo" id="aadi" src="<?php echo getResim($this->birey["id"]); ?>" alt="Resim Yok" itemprop="photo" />
	<h3 itemprop="name" class="structured name bday"><?php echo $this->birey["ad"]." (".$this->birey['Detay']["dogum"].($this->birey['Detay']["olum"]=="0000-00-00" ? "" : " / ".$this->birey['Detay']["olum"]).")"; ?></h3>
	<div id="ratew" rev="vote-abstain">
		<div class="s_1 rates"></div>
		<div class="s_2 rates"></div>
		<div class="s_3 rates"></div>
		<div class="s_4 rates"></div>
		<div class="s_5 rates"></div>
		<div class="stv">Oy Sonucu</div>
	</div>
	<div id="resimUpload">Resmi Güncelle<br />En Fazla Boyut:2MB</div>
	<p class="cssc">
		<b>Eşi:</b><span id="aaes" itemprop="darling"><?php echo $this->birey['Detay']["es"]; ?></span><br />
		<b>Adres:</b><span itemprop="address" class="adr"><?php echo $this->birey['Detay']["adres"]; ?></span><br />
		<b>Mail:</b><span itemprop="email" class="email"><?php echo $this->birey['Detay']["mail"]; ?></span><br />
		<b>Tel:</b><span itemprop="tel" class="tel"><?php echo $this->birey['Detay']["tel"]; ?></span><br />
		<b><a id="bft" title="Twitter mesajlarını göster">Twitter:</a></b><span id="aadt" class="mod" itemprop="twitter"><?php echo $this->birey['Detay']["twitter"]; ?></span>
		<b class="sakla">Flickr:</b><span id="aadf" class="sakla"><?php echo $this->birey['Detay']["flickr"]; ?></span>
	</p><br />
	<p id="aatanim"><?php echo $this->birey['Detay']["tanim"]; ?></p><br />
	<a href="/main/aile/form/<?php echo $this->birey["id"]; ?>" id="abdb" class="boubleButton blue">Güncelle</a>
	<h4 class="cmnt_hdr"><span><?php echo $this->yTotal; ?></span> Yorum...</h4>
	<div id="comments"><?php echo $this->yorumlar; ?></div>
</article>
<fieldset>
	<legend class="radial daire">Bir Yorum Ekle</legend>
	<br class="clear" />
	<form id="adf" method="post" action="">
		<p><input type="hidden" id="aidh" name="aidh" value="<?php echo $this->birey["id"]; ?>" /></p>
		<p><input class="name" name="acn" required aria-required /><label for="acn"><abbr title="Doldurulması zorunludur">*</abbr>Adınız</label></p>
		<p><input type="email" name="ace" required aria-required /><label for="ace"><abbr title="Doldurulması zorunludur. Kimseye verilmeyecek veya sitede gösterilmeyecektir.">*</abbr>Email</label></p>
		<p><input type="url" name="acu" placeholder="http://"/><label for="acu">Website</label></p>
		<p><label for="acb" class="sakla">Yorum:</label><textarea name="acb" cols="20" rows="5" required aria-required maxlength="500" ></textarea></p>
		<br />
		<p><input type="submit" class="boubleButton blue" /></p>
	</form>
</fieldset>
</div> 

<aside id="rcnt" role=”complementary”>
	<?php echo $this->ara(); ?><br />
	<fieldset id="aliste" class="gradient border">
		<legend class="ui-widget ui-widget-header ui-corner-all">Aile Ağacı</legend>
		<ul>
		<?php
			foreach ($this->aileListe as $row)
			{
				$liste[$row['id']]=$row['ad'];
				$ebeveyn[$row['id']]=$row['eid'];
			}
			aileListeDoldur($liste,$ebeveyn,0);
			function aileListeDoldur($liste,$ebeveyn,$aileArray)
			{
				$aileArray=array_keys($ebeveyn,$aileArray);
				foreach($aileArray as $value)
				{
					$ulEkle=array_keys($ebeveyn,$value);
					echo "\n\r<li id='".$value."-".$liste[$value]."'><a class='url fn' href='/main/aile?id=".$value."' rel='contact met kin'>".$liste[$value]."</a>";
					if($ulEkle)	
					{	
						echo "<ul>";
						aileListeDoldur($liste,$ebeveyn,$value);
						echo "</ul></li>";
					}
					else echo "</li>";
				}
			}
		?>
		</ul>
		<hr />
		<p><span class="uyari">1 Tık:</span>Bireyin çocuklarını göster/gizle.</p>
		<p><span class="uyari">2 Tık:</span>Bireyin bilgilerine bak.</p>
		<p><span class="uyari">3 Tık:</span>Bireyi güncelle.</p>
	</fieldset><br />
	<section class="infCour border shadow">
		<div class="wic">
			<ul>
			<?php
				$i=1;
				foreach ($this->aileListe as $row)
					echo "<li><figure title='".$row['ad']."' class='transition' tabindex='".$i++."'><span></span><img aria-haspopup='true' src='".getResim($row['id'])."' height='75' width='85' alt='".$row['ad']."'/><figcaption>".$row['ad']."</figcaption></figure></li>\n";
			?>	
			</ul>
		</div>
	</section><br />
	<div id="dialog" class="sakla"><img src="<?php echo getResim(0); ?>" alt='Aile Birey Resmi' /></div>
	<section class="border">
		<h4 class="st_r ui-widget ui-widget-header ui-corner-top">İstatistik</h4>
		<p><?php echo ($this->bekar+$this->evli)." birey kayıtlı.".$this->bekar." bekar,".$this->evli." evli.".$this->canli." kişi hayatta."; ?></p><br />
		<p><?php echo $this->tag; ?></p>
	</section>
<div class="flickr_photobar">
	<div id="flickr_overlay" class="flickr_overlay" style="display:none;"></div>
	<div id="flickr_photopreview" class="photopreview" style="display:none;">
		<div class="preview_wrapper">
			<div class="preview">
				<div class="loading"></div>
				<div id="preview_close" class="close escBlue"></div>
				<span id="large_phototitle"></span>
				<!--image-->
				<a href="#" id="preview_img_next" class="img_next nextArrow">Sonraki</a>
				<a href="#" id="preview_img_prev" class="img_prev prevArrow">Önceki</a>
			</div>
		</div>
	</div>
	<div id="photobar" class="photobar">	
		<div class="thumbs albums" id="sets">
			<a href="#" class="prev prevArrow">Önceki</a>
			<div class="thumbsWrapper"><ul></ul></div>
			<a href="#" class="next nextArrow">Sonraki</a>
		</div>
		<nav role="navigation" class="thumbs images" id="images" style="bottom:-125px;">
			<a href="#" class="prev prevArrow">Önceki</a>
			<div class="thumbsWrapper"><ul></ul></div>
			<a href="#" class="next nextArrow">Sonraki</a>
			<span class="images_toggle"><span id="setName"></span><a id="images_toggle">Setler</a></span>
		</nav>
		<a id="flickr_toggle" class="toggle">Flickr Fotoğrafları<span class="sakla loading_small"></span></a>
	</div>
</div>
<br class="clear" />
<script async="async" src="http://www.appelsiini.net/download/jquery.viewport.mini.js"></script>
