<h3 class="ui-widget ui-widget-header">Aile Resimleri</h3>
<div id="arsc">
	<div id="arjc">
		<img id="arji" src="http://farm5.static.flickr.com/4082/4758467508_3510ce683e.jpg" alt="" />
		<h4 id="arjit"></h4>
	</div><br />
	<ul id="arnc" role="navigation">
		<li><a id="arpi" href="#">Önceki</a></li>
		<li id="aric">1 / 1</li>
		<li><a id="arni" href="#">Sonraki</a></li>
		<li class="arsi sakla">
			<a id="arsss" href="#">Resimler aksın</a>
			<a id="arstop" href="#">Resimler dursun</a>
		</li>
	</ul>
	<div id="arjt" class="border gradient"></div>
</div>
</div>

<aside id="rcnt" role=”complementary”>
<nav role="navigation" id="jas-nav">
	<h3 class="radial daire">Kişiler</h3>
	<p>
		<input type="checkbox" id="arjsat" checked />
		<label for="arjsat">Hepsini Seç</label>
	</p>
</nav>
<br class="clear" />
