<h3 class="ui-widget ui-widget-header">Aile Resimleri</h3>
<div id="slideContainer">
	<div id="jas-container">
		<img id="jas-image" src="http://farm5.static.flickr.com/4082/4758467508_3510ce683e.jpg" alt="" />
		<h4 id="jas-image-text"></h4>
	</div><br />
	<ul id="navigation-controls" role="navigation">
		<li><a id="previous-image" href="#">Önceki</a></li>
		<li id="image-counter">1 / 1</li>
		<li><a id="next-image" href="#">Sonraki</a></li>
		<li class="slideshow-item sakla">
			<a id="start-slideshow" href="#">Resimler aksın</a>
			<a id="stop-slideshow" href="#">Resimler dursun</a>
		</li>
	</ul>
	<div id="jas-thumbnails" class="border gradient"></div>
</div>
</div>

<aside id="rcnt" role=”complementary”>
<nav role="navigation" id="jas-nav">
	<h3 class="radial daire">Kişiler</h3>
	<p>
		<input type="checkbox" id="jas-select-all-tags" checked />
		<label for="jas-select-all-tags">Hepsini Seç</label>
	</p>
</nav>
<br class="clear" />
<script src="http://github.com/cowboy/jquery-dotimeout/raw/v1.0/jquery.ba-dotimeout.min.js"></script>
