<h3 class="ui-widget ui-widget-header">Aile Resimleri</h3>
<div id="arsc" aria-live="assertive" aria-atomic="true" >
	<div id="arjc">
		<img id="arji" src="http://farm5.static.flickr.com/4082/4758467508_3510ce683e.jpg" alt="" />
		<h4 id="arjit"></h4>
	</div><br />
	<div id="arnc" role="navigation">
		<a id="arpi" href="#"><<</a>
		<span id="aric">1 / 1</span>
		<a id="arni" href="#">>></a>
		<div class="arsi sakla">
			<a id="arsss" href="#">Slayt</a>
			<a id="arstop" href="#">Durdur</a>
		</div>
	</div>
	<div id="arjt" class="border gradient"></div>
</div>
</div>

<aside id="rcnt" role=”complementary”>
<nav role="navigation" id="jas-nav">
	<h3 class="radial daire">Kişiler</h3>
	<p>
		<input type="checkbox" id="arjsat" checked />
		<label for="arjsat">Hepsini Seç</label>
	</p>
</nav>
<br class="clear" />
