	<h3 class="ui-widget ui-widget-header">Nilgünün Düğünü #1</h3>
	<div id="aileVideoDiv">
		<video onended="yeniVideo()" controls autoplay="true"><!-- onmouseover="this.play()" onmouseout="this.pause()" -->
			<source src="http://ibrahimtasdemir.mysites.com/get_file/26062010035.mp4" type='video/mp4'></source>
			<source src="http://ibrahimtasdemir.mysites.com/get_file/26062010035.webm" type='video/webm'></source>
			<source src="http://ibrahimtasdemir.mysites.com/get_file/26062010035.ogv" type='video/ogg'></source>
		</video>
		<canvas id="reflection" height="55"></canvas>
		<p class="uyari"><strong>Görüntüyü indir:</strong>
			<a target="_blank" rel="nofollow" href="http://ibrahimtasdemir.mysites.com/get_file/26062010035.mp4">"MP4"</a>,<a target="_blank" rel="nofollow" href="http://ibrahimtasdemir.mysites.com/get_file/26062010035.ogv">"OGG"</a>,<a target="_blank" rel="nofollow" href="http://ibrahimtasdemir.mysites.com/get_file/26062010035.webm">"WEBM"</a>
		</p>
	</div>
</div>
<aside id="rcnt" role=”complementary”>
<div class="rslink" id="vidLink">
<p><a class="translate3" id="26062010035" data-sira="0"><img class="transition" src="/main/images/film/back.png" alt="Seç" />Nilgünün Düğünü #1</a></p><br />
<p><a id="26062010036" data-sira="1"><img class="transition" src="/main/images/film/back.png" alt="Seç" />Nilgünün Düğünü #2</a></p><br />
<p><a id="26062010037" data-sira="2"><img class="transition" src="/main/images/film/back.png" alt="Seç" />Nilgünün Düğünü #3</a></p><br />
<p><a id="26062010038" data-sira="3"><img class="transition" src="/main/images/film/back.png" alt="Seç" />Nilgünün Düğünü #4</a></p><br />
</div>
